...

diff --git a/foo/d b/foo/d
--- a/foo/d
+++ b/foo/d
@@ -1,18 +1,11 @@
 #!/bin/bash
-SRC=code.cpp
-EXE=a.out
-
-g++ -std=c++17 -DLOCAL -Wshadow -Wall -g -fsanitize=address -fsanitize=undefined -D_GLIBCXX_DEBUG -fmax-errors=2 $SRC -o $EXE
-
-if [ $? -ne 0 ]; then
-    echo "Compilation failed!"
-    exit 1
-fi
-
-echo 
-echo "Input:"
-cat "$1"
+g++ -std=c++23 -DLOCAL -Wshadow -Wall -g -fsanitize=address \
+ -fsanitize=undefined -D_GLIBCXX_DEBUG -fmax-errors=2 code.cpp\
+ -o a.out || { echo "Compilation failed!"; exit 1; }
 echo
-echo "Output:"
-"./$EXE" < "$1"
+echo Input:
+cat $1
+echo
+echo Output:
+./a.out < $1
 echo
