...

diff --git a/foo/d b/foo/d
--- a/foo/d
+++ b/foo/d
@@ -1,7 +1,11 @@
 #!/bin/bash
-g++ -std=c++23 -DLOCAL -Wshadow -Wall -g -fsanitize=address \
- -fsanitize=undefined -D_GLIBCXX_DEBUG -fmax-errors=2 code.cpp\
- -o a.out || { echo "Compilation failed!"; exit 1; }
+if ! g++ -std=c++23 -DLOCAL -Wshadow -Wall -g \
+ -fsanitize=address -fsanitize=undefined -D_GLIBCXX_DEBUG \
+ -fmax-errors=2 code.cpp -o a.out
+then
+    echo "Compilation failed!"
+    exit 1
+fi
 echo
 echo Input:
 cat $1
